# Generated by Django 2.0.3 on 2018-03-11 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('version', models.IntegerField(unique=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.DeploymentConfig')),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_filename', models.CharField(max_length=256)),
                ('file_contents', models.TextField(default='')),
                ('is_executable', models.BooleanField(default=False)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.DeploymentConfig')),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=64)),
                ('parameter_value', models.CharField(max_length=512)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.Deployment')),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit', models.CharField(default='master', max_length=256)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.DeploymentConfig')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_path', models.CharField(max_length=2048)),
                ('local_path', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryBuildOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=256)),
                ('option_command', models.CharField(max_length=1024)),
                ('option_priority', models.IntegerField(default=1)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.Repository')),
            ],
        ),
        migrations.AddField(
            model_name='deploymentrepository',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.Repository'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ui.DeploymentConfig'),
        ),
    ]
