# Generated by Django 2.0.3 on 2018-03-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentconfig',
            name='version',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='deploymentconfig',
            unique_together={('name', 'version')},
        ),
    ]
