# Generated by Django 2.0.3 on 2018-03-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20180311_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deploymentfile',
            name='file_contents',
            field=models.TextField(blank=True, default=''),
        ),
    ]
