# Generated by Django 2.0.3 on 2018-03-13 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_auto_20180313_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDefaultParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=64)),
                ('parameter_value', models.CharField(max_length=512)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.DeploymentFile')),
            ],
        ),
    ]
