# Generated by Django 2.0.3 on 2018-03-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_deployment_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentconfig',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
