# Generated by Django 2.0.3 on 2018-03-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_auto_20180313_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='local_path',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='remote_path',
            field=models.CharField(max_length=2048, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='deploymentfile',
            unique_together={('deployment', 'target_filename')},
        ),
        migrations.AlterUniqueTogether(
            name='deploymentrepository',
            unique_together={('deployment', 'repo')},
        ),
        migrations.AlterUniqueTogether(
            name='filedefaultparameter',
            unique_together={('file', 'parameter_name')},
        ),
    ]
