# Generated by Django 2.0.3 on 2018-03-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_filedefaultparameter_is_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedefaultparameter',
            name='parameter_value',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
