# Generated by Django 2.0.3 on 2018-03-14 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0010_firmware'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ui.Deployment')),
            ],
        ),
    ]
