# Generated by Django 2.0.3 on 2018-03-14 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0011_runningdeployment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningdeployment',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.Deployment'),
        ),
    ]
