# Generated by Django 2.0.3 on 2018-03-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0012_auto_20180314_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningdeployment',
            name='status',
            field=models.TextField(blank='', default=''),
        ),
    ]
