# Generated by Django 2.0.3 on 2018-03-14 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0013_runningdeployment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningdeployment',
            name='deployment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui.Deployment'),
        ),
    ]
