# Generated by Django 2.0.3 on 2018-03-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0014_auto_20180314_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
