# Generated by Django 2.0.3 on 2018-03-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0015_auto_20180320_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='local_cache',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
